/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sk_hellojni_HelloJni */

#ifndef _Included_com_sk_hellojni_HelloJni
#define _Included_com_sk_hellojni_HelloJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sk_hellojni_HelloJni
 * Method:    AddNumber
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_sk_hellojni_HelloJni_AddNumber
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
