/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_test_CreateFile */

#ifndef _Included_com_example_test_CreateFile
#define _Included_com_example_test_CreateFile
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_test_CreateFile
 * Method:    createFile
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_test_CreateFile_createFile
  (JNIEnv * env, jobject jobj, jstring jFileName);

JNIEXPORT void JNICALL Java_com_example_test_CreateFile_initLibPath
    (JNIEnv * env, jobject jobj, jstring jFileName, jstring jLibPath);

#ifdef __cplusplus
}
#endif
#endif
